name: render_ffmpeg
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  ffmpeg_kit_flutter: ^6.0.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1
  video_player: ^2.7.1
  image_gallery_saver: ^2.0.3
  fluttertoast: ^8.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/


