name: du_icons
description: A new Flutter project.
repository: https://github.com/the-ego/samples/tree/main/du_icons
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.19.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
flutter:
  fonts:
    - family: DUIcons
      fonts:
        - asset: assets/DUIcons.ttf

topics:
  - assets
  - icons
  - ui